### PR TITLE
fix: the closing tag was missing from the li element in html of the example addon code

### PR DESCRIPTION
**Pull request by HarikrishnanBalagopal**
Signed-off-by: Harikrishnan Balagopal <harikrishmenon@gmail.com>

### CODE REVIEW

**Comment by HarikrishnanBalagopal** [comment]
Fixes: #193

**Comment by aufi** [comment]
Thanks for the fix @HarikrishnanBalagopal! May I ask you for not changing formatting (removal of empty comments and import order change)?

**Comment by HarikrishnanBalagopal** [comment]
> May I ask you for not changing formatting (removal of empty comments and import order change)?

It's Golang fmt command https://pkg.go.dev/fmt that runs automatically when you save the file.

**Review by aufi — APPROVED** [review]
Thanks! Looks good to me.

**Comment by aufi** [comment]
> > May I ask you for not changing formatting (removal of empty comments and import order change)?
> 
> It was done by the Golang `fmt` command https://pkg.go.dev/fmt that runs automatically when you save the file in VSCode. I have made the changes you requested.

@HarikrishnanBalagopal  It seems most devs use GoLand which formates it in that way. Actually I use VScode too, it is possible adjust Format Tool in go extension settings. I'm not sure it is the best solution, but somehow works for me.
image

**Pull request merged**
